[package]
name = "parsort"
version = "0.1.0"
authors = ["Noam Koren <noam575@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# rand = "0.8"
